[2024-09-01T17:51:25.448+0000] {processor.py:157} INFO - Started process (PID=7497) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:25.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:51:25.451+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:51:25.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:25.845+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:51:25.841+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:51:25.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:25.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.421 seconds
[2024-09-01T17:51:55.919+0000] {processor.py:157} INFO - Started process (PID=7557) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:55.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:51:55.922+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:51:55.922+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:56.288+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:51:56.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:51:56.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:51:56.303+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.386 seconds
[2024-09-01T17:52:26.354+0000] {processor.py:157} INFO - Started process (PID=7617) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:26.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:52:26.357+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:52:26.357+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:26.702+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:52:26.697+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:52:26.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:26.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.364 seconds
[2024-09-01T17:52:57.205+0000] {processor.py:157} INFO - Started process (PID=7684) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:57.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:52:57.212+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:52:57.212+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:57.571+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:52:57.568+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:52:57.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:52:57.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.385 seconds
[2024-09-01T17:53:27.889+0000] {processor.py:157} INFO - Started process (PID=7744) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:27.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:53:27.892+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:53:27.892+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:28.261+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:53:28.256+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:53:28.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:28.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.388 seconds
[2024-09-01T17:53:58.445+0000] {processor.py:157} INFO - Started process (PID=7804) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:58.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:53:58.448+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:53:58.447+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:58.838+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:53:58.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:53:58.839+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:53:58.854+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.412 seconds
[2024-09-01T17:54:29.145+0000] {processor.py:157} INFO - Started process (PID=7864) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:54:29.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:54:29.148+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:54:29.148+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:54:29.524+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:54:29.520+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:54:29.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:54:29.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.396 seconds
[2024-09-01T17:54:59.876+0000] {processor.py:157} INFO - Started process (PID=7924) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:54:59.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:54:59.879+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:54:59.878+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:55:00.317+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:55:00.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:55:00.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:55:00.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.458 seconds
[2024-09-01T17:55:30.617+0000] {processor.py:157} INFO - Started process (PID=7982) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:55:30.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:55:30.620+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:55:30.619+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:55:30.993+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:55:30.988+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:55:30.994+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:55:31.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.402 seconds
[2024-09-01T17:56:01.056+0000] {processor.py:157} INFO - Started process (PID=8042) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:01.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:56:01.059+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:56:01.059+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:01.438+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:56:01.435+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:56:01.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:01.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.400 seconds
[2024-09-01T17:56:32.301+0000] {processor.py:157} INFO - Started process (PID=8102) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:32.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:56:32.304+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:56:32.304+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:32.687+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:56:32.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:56:32.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:56:32.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.404 seconds
[2024-09-01T17:57:03.478+0000] {processor.py:157} INFO - Started process (PID=8162) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:03.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:57:03.481+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:57:03.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:03.873+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:57:03.869+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:57:03.874+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:03.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.415 seconds
[2024-09-01T17:57:34.827+0000] {processor.py:157} INFO - Started process (PID=8222) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:34.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:57:34.831+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:57:34.830+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:35.211+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:57:35.207+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:57:35.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:57:35.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.408 seconds
[2024-09-01T17:58:05.881+0000] {processor.py:157} INFO - Started process (PID=8282) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:05.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:58:05.884+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:58:05.884+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:06.239+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:58:06.236+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:58:06.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:06.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.375 seconds
[2024-09-01T17:58:36.392+0000] {processor.py:157} INFO - Started process (PID=8342) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:36.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:58:36.395+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:58:36.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:36.754+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:58:36.749+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:58:36.755+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:58:36.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.386 seconds
[2024-09-01T17:59:07.762+0000] {processor.py:157} INFO - Started process (PID=8402) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:07.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:59:07.765+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:59:07.765+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:08.240+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:59:08.236+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:59:08.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:08.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.498 seconds
[2024-09-01T17:59:38.893+0000] {processor.py:157} INFO - Started process (PID=8462) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:38.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T17:59:38.895+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:59:38.895+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:39.283+0000] {logging_mixin.py:154} INFO - [2024-09-01T17:59:39.278+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T17:59:39.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T17:59:39.299+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.409 seconds
[2024-09-01T18:00:09.344+0000] {processor.py:157} INFO - Started process (PID=8522) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:09.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:00:09.347+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:00:09.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:09.727+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:00:09.723+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:00:09.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:09.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.402 seconds
[2024-09-01T18:00:39.941+0000] {processor.py:157} INFO - Started process (PID=8582) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:39.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:00:39.944+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:00:39.944+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:40.320+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:00:40.316+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:00:40.322+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:00:40.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.398 seconds
[2024-09-01T18:03:46.858+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:03:46.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:03:46.861+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:03:46.861+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:03:47.905+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:03:47.901+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:03:47.906+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:03:47.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.066 seconds
[2024-09-01T18:04:18.550+0000] {processor.py:157} INFO - Started process (PID=116) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:18.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:04:18.553+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:04:18.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:18.936+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:04:18.932+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:04:18.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:18.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.403 seconds
[2024-09-01T18:04:49.028+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:49.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:04:49.030+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:04:49.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:49.445+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:04:49.442+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:04:49.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:04:49.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.437 seconds
[2024-09-01T18:05:19.924+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:19.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:05:19.927+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:05:19.927+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:20.310+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:05:20.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:05:20.311+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:20.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.403 seconds
[2024-09-01T18:05:51.247+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:51.247+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:05:51.249+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:05:51.249+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:51.620+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:05:51.616+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:05:51.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:05:51.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.390 seconds
[2024-09-01T18:06:21.974+0000] {processor.py:157} INFO - Started process (PID=365) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:21.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:06:21.977+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:06:21.977+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:22.339+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:06:22.335+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:06:22.341+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:22.356+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.385 seconds
[2024-09-01T18:06:52.611+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:52.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:06:52.614+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:06:52.614+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:53.018+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:06:53.014+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:06:53.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:06:53.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.425 seconds
[2024-09-01T18:07:23.360+0000] {processor.py:157} INFO - Started process (PID=485) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:23.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:07:23.363+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:07:23.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:23.801+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:07:23.797+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:07:23.802+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:23.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.460 seconds
[2024-09-01T18:07:54.170+0000] {processor.py:157} INFO - Started process (PID=545) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:54.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:07:54.173+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:07:54.173+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:54.532+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:07:54.528+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:07:54.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:07:54.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.381 seconds
[2024-09-01T18:08:24.632+0000] {processor.py:157} INFO - Started process (PID=605) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:24.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:08:24.635+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:08:24.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:25.014+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:08:25.010+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:08:25.016+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:25.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.401 seconds
[2024-09-01T18:08:56.009+0000] {processor.py:157} INFO - Started process (PID=665) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:56.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:08:56.012+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:08:56.012+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:56.382+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:08:56.378+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:08:56.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:08:56.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.394 seconds
[2024-09-01T18:09:26.437+0000] {processor.py:157} INFO - Started process (PID=725) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:26.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:09:26.439+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:09:26.439+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:26.819+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:09:26.816+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:09:26.820+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:26.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.405 seconds
[2024-09-01T18:09:57.195+0000] {processor.py:157} INFO - Started process (PID=785) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:57.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:09:57.197+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:09:57.197+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:57.588+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:09:57.584+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:09:57.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:09:57.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.410 seconds
[2024-09-01T18:10:27.758+0000] {processor.py:157} INFO - Started process (PID=845) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:27.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:10:27.761+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:10:27.761+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:28.110+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:10:28.107+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:10:28.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:28.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.370 seconds
[2024-09-01T18:10:58.343+0000] {processor.py:157} INFO - Started process (PID=907) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:58.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:10:58.346+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:10:58.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:58.719+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:10:58.714+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:10:58.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:10:58.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.393 seconds
[2024-09-01T18:11:29.663+0000] {processor.py:157} INFO - Started process (PID=967) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:11:29.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:11:29.666+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:11:29.665+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:11:30.017+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:11:30.014+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:11:30.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:11:30.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.371 seconds
[2024-09-01T18:12:00.855+0000] {processor.py:157} INFO - Started process (PID=1027) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:00.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:12:00.858+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:12:00.858+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:01.219+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:12:01.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:12:01.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:01.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.382 seconds
[2024-09-01T18:12:31.706+0000] {processor.py:157} INFO - Started process (PID=1087) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:31.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:12:31.709+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:12:31.709+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:32.075+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:12:32.071+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:12:32.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:12:32.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.388 seconds
[2024-09-01T18:13:02.732+0000] {processor.py:157} INFO - Started process (PID=1147) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:02.733+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:13:02.735+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:13:02.735+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:03.111+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:13:03.107+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:13:03.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:03.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.397 seconds
[2024-09-01T18:13:33.906+0000] {processor.py:157} INFO - Started process (PID=1207) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:33.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:13:33.909+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:13:33.909+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:34.302+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:13:34.298+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:13:34.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:13:34.320+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.416 seconds
[2024-09-01T18:14:05.127+0000] {processor.py:157} INFO - Started process (PID=1267) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:05.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:14:05.131+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:14:05.130+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:05.410+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:14:05.405+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:14:05.411+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:05.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.301 seconds
[2024-09-01T18:14:36.022+0000] {processor.py:157} INFO - Started process (PID=1327) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:36.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:14:36.026+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:14:36.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:36.311+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:14:36.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:14:36.312+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:14:36.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.309 seconds
[2024-09-01T18:15:06.912+0000] {processor.py:157} INFO - Started process (PID=1387) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:06.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:15:06.915+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:15:06.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:07.193+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:15:07.189+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:15:07.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:07.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.302 seconds
[2024-09-01T18:15:37.776+0000] {processor.py:157} INFO - Started process (PID=1447) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:37.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:15:37.778+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:15:37.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:38.051+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:15:38.046+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:15:38.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:15:38.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.297 seconds
[2024-09-01T18:16:08.565+0000] {processor.py:157} INFO - Started process (PID=1507) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:08.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:16:08.568+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:16:08.567+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:08.829+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:16:08.824+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:16:08.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:08.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.286 seconds
[2024-09-01T18:16:39.343+0000] {processor.py:157} INFO - Started process (PID=1567) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:39.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:16:39.346+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:16:39.345+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:39.602+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:16:39.598+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:16:39.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:16:39.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.279 seconds
[2024-09-01T18:17:10.153+0000] {processor.py:157} INFO - Started process (PID=1627) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:10.154+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:17:10.156+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:17:10.156+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:10.440+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:17:10.435+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:17:10.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:10.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.305 seconds
[2024-09-01T18:17:40.944+0000] {processor.py:157} INFO - Started process (PID=1687) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:40.945+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:17:40.948+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:17:40.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:41.247+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:17:41.243+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:17:41.248+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:17:41.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.322 seconds
[2024-09-01T18:18:11.780+0000] {processor.py:157} INFO - Started process (PID=1747) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:11.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:18:11.782+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:18:11.782+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:12.042+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:18:12.038+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:18:12.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:12.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.281 seconds
[2024-09-01T18:18:42.513+0000] {processor.py:157} INFO - Started process (PID=1808) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:42.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:18:42.516+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:18:42.516+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:42.794+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:18:42.790+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:18:42.796+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:18:42.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.301 seconds
[2024-09-01T18:19:13.628+0000] {processor.py:157} INFO - Started process (PID=1868) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:13.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:19:13.632+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:19:13.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:13.894+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:19:13.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:19:13.896+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:13.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.290 seconds
[2024-09-01T18:19:44.876+0000] {processor.py:157} INFO - Started process (PID=1928) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:44.877+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:19:44.879+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:19:44.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:45.166+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:19:45.162+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:19:45.168+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:19:45.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.310 seconds
[2024-09-01T18:20:15.918+0000] {processor.py:157} INFO - Started process (PID=1988) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:15.919+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:20:15.921+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:20:15.920+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:16.181+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:20:16.176+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:20:16.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:16.198+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.283 seconds
[2024-09-01T18:20:46.694+0000] {processor.py:157} INFO - Started process (PID=2048) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:46.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:20:46.696+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:20:46.696+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:46.984+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:20:46.979+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:20:46.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:20:47.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.311 seconds
[2024-09-01T18:21:17.817+0000] {processor.py:157} INFO - Started process (PID=2108) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:17.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:21:17.820+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:21:17.820+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:18.085+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:21:18.080+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:21:18.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:18.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.286 seconds
[2024-09-01T18:21:48.179+0000] {processor.py:157} INFO - Started process (PID=2168) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:48.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:21:48.182+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:21:48.181+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:48.453+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:21:48.450+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:21:48.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:21:48.469+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.293 seconds
[2024-09-01T18:22:19.220+0000] {processor.py:157} INFO - Started process (PID=2228) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:19.221+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:22:19.223+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:22:19.223+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:19.500+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:22:19.496+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:22:19.501+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:19.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.300 seconds
[2024-09-01T18:22:50.144+0000] {processor.py:157} INFO - Started process (PID=2295) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:50.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:22:50.147+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:22:50.146+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:50.417+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:22:50.412+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:22:50.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:22:50.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.292 seconds
[2024-09-01T18:23:21.134+0000] {processor.py:157} INFO - Started process (PID=2355) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:21.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:23:21.137+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:23:21.137+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:21.404+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:23:21.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:23:21.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:21.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.292 seconds
[2024-09-01T18:23:52.241+0000] {processor.py:157} INFO - Started process (PID=2415) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:52.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:23:52.244+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:23:52.243+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:52.513+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:23:52.509+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:23:52.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:23:52.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.294 seconds
[2024-09-01T18:24:23.400+0000] {processor.py:157} INFO - Started process (PID=2475) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:23.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:24:23.403+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:24:23.403+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:23.684+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:24:23.680+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:24:23.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:23.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.305 seconds
[2024-09-01T18:24:54.608+0000] {processor.py:157} INFO - Started process (PID=2535) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:54.609+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:24:54.611+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:24:54.611+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:54.910+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:24:54.905+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:24:54.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:24:54.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.323 seconds
[2024-09-01T18:25:25.497+0000] {processor.py:157} INFO - Started process (PID=2595) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:25.498+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:25:25.500+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:25:25.499+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:25.800+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:25:25.795+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:25:25.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:25.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.323 seconds
[2024-09-01T18:25:56.477+0000] {processor.py:157} INFO - Started process (PID=2655) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:56.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:25:56.480+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:25:56.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:56.749+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:25:56.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:25:56.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:25:56.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.292 seconds
[2024-09-01T18:26:27.377+0000] {processor.py:157} INFO - Started process (PID=2715) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:27.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:26:27.379+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:26:27.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:27.663+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:26:27.658+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:26:27.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:27.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.306 seconds
[2024-09-01T18:26:58.511+0000] {processor.py:157} INFO - Started process (PID=2775) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:58.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:26:58.513+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:26:58.513+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:58.776+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:26:58.772+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:26:58.777+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:26:58.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.284 seconds
[2024-09-01T18:27:29.371+0000] {processor.py:157} INFO - Started process (PID=2835) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:27:29.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:27:29.375+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:27:29.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:27:29.658+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:27:29.654+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:27:29.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:27:29.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.306 seconds
[2024-09-01T18:28:00.271+0000] {processor.py:157} INFO - Started process (PID=2895) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:00.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:28:00.273+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:28:00.273+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:00.548+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:28:00.545+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:28:00.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:00.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.297 seconds
[2024-09-01T18:28:31.410+0000] {processor.py:157} INFO - Started process (PID=2955) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:31.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:28:31.413+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:28:31.412+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:31.688+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:28:31.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:28:31.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:28:31.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.299 seconds
[2024-09-01T18:29:02.399+0000] {processor.py:157} INFO - Started process (PID=3015) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:02.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:29:02.404+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:29:02.403+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:02.670+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:29:02.665+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:29:02.672+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:02.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.291 seconds
[2024-09-01T18:29:33.454+0000] {processor.py:157} INFO - Started process (PID=3075) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:33.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:29:33.456+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:29:33.456+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:33.726+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:29:33.721+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:29:33.727+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:29:33.746+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.295 seconds
[2024-09-01T18:30:04.408+0000] {processor.py:157} INFO - Started process (PID=3135) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:04.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:30:04.411+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:30:04.410+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:04.686+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:30:04.681+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:30:04.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:04.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.299 seconds
[2024-09-01T18:30:35.422+0000] {processor.py:157} INFO - Started process (PID=3195) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:35.423+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:30:35.425+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:30:35.425+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:35.697+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:30:35.692+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:30:35.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:30:35.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.297 seconds
[2024-09-01T18:31:06.300+0000] {processor.py:157} INFO - Started process (PID=3255) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:06.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:31:06.303+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:31:06.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:06.572+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:31:06.567+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:31:06.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:06.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.291 seconds
[2024-09-01T18:31:37.149+0000] {processor.py:157} INFO - Started process (PID=3315) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:37.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:31:37.153+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:31:37.153+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:37.413+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:31:37.408+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:31:37.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:31:37.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.283 seconds
[2024-09-01T18:32:07.963+0000] {processor.py:157} INFO - Started process (PID=3375) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:07.964+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:32:07.966+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:32:07.965+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:08.237+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:32:08.233+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:32:08.238+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:08.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.297 seconds
[2024-09-01T18:32:38.807+0000] {processor.py:157} INFO - Started process (PID=3435) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:38.808+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:32:38.810+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:32:38.810+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:39.102+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:32:39.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:32:39.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:32:39.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.315 seconds
[2024-09-01T18:33:09.994+0000] {processor.py:157} INFO - Started process (PID=3495) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:09.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:33:09.998+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:33:09.998+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:10.279+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:33:10.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:33:10.280+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:10.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.306 seconds
[2024-09-01T18:33:41.102+0000] {processor.py:157} INFO - Started process (PID=3556) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:41.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:33:41.106+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:33:41.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:41.404+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:33:41.399+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:33:41.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:33:41.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.324 seconds
[2024-09-01T18:34:12.180+0000] {processor.py:157} INFO - Started process (PID=3616) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:12.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:34:12.183+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:34:12.183+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:12.479+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:34:12.474+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:34:12.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:12.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.321 seconds
[2024-09-01T18:34:42.568+0000] {processor.py:157} INFO - Started process (PID=3676) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:42.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:34:42.570+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:34:42.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:42.850+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:34:42.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:34:42.852+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:34:42.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.306 seconds
[2024-09-01T18:35:13.621+0000] {processor.py:157} INFO - Started process (PID=3736) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:13.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:35:13.624+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:35:13.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:13.903+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:35:13.898+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:35:13.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:13.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.302 seconds
[2024-09-01T18:35:44.845+0000] {processor.py:157} INFO - Started process (PID=3796) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:44.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:35:44.848+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:35:44.848+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:45.142+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:35:45.134+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:35:45.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:35:45.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.323 seconds
[2024-09-01T18:36:15.919+0000] {processor.py:157} INFO - Started process (PID=3856) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:15.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:36:15.923+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:36:15.922+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:16.220+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:36:16.216+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:36:16.221+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:16.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.321 seconds
[2024-09-01T18:36:46.984+0000] {processor.py:157} INFO - Started process (PID=3916) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:46.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:36:46.987+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:36:46.987+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:47.274+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:36:47.270+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:36:47.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:36:47.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.313 seconds
[2024-09-01T18:37:17.563+0000] {processor.py:157} INFO - Started process (PID=3976) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:17.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:37:17.566+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:37:17.565+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:17.848+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:37:17.843+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:37:17.849+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:17.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.305 seconds
[2024-09-01T18:37:47.931+0000] {processor.py:157} INFO - Started process (PID=4036) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:47.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:37:47.933+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:37:47.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:48.218+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:37:48.213+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:37:48.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:37:48.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.315 seconds
[2024-09-01T18:38:19.007+0000] {processor.py:157} INFO - Started process (PID=4096) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:19.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:38:19.011+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:38:19.010+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:19.301+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:38:19.297+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:38:19.302+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:19.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.319 seconds
[2024-09-01T18:38:50.269+0000] {processor.py:157} INFO - Started process (PID=4156) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:50.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:38:50.272+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:38:50.272+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:50.548+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:38:50.543+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:38:50.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:38:50.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.300 seconds
[2024-09-01T18:39:21.260+0000] {processor.py:157} INFO - Started process (PID=4223) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:21.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:39:21.263+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:39:21.263+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:21.527+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:39:21.522+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:39:21.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:21.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.286 seconds
[2024-09-01T18:39:52.336+0000] {processor.py:157} INFO - Started process (PID=4283) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:52.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:39:52.339+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:39:52.339+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:52.610+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:39:52.605+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:39:52.611+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:39:52.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.293 seconds
[2024-09-01T18:40:23.366+0000] {processor.py:157} INFO - Started process (PID=4343) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:23.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:40:23.368+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:40:23.368+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:23.629+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:40:23.624+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:40:23.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:23.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.286 seconds
[2024-09-01T18:40:54.434+0000] {processor.py:157} INFO - Started process (PID=4403) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:54.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:40:54.437+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:40:54.437+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:54.708+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:40:54.703+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:40:54.710+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:40:54.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.293 seconds
[2024-09-01T18:41:25.180+0000] {processor.py:157} INFO - Started process (PID=4463) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:25.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:41:25.183+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:41:25.182+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:25.453+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:41:25.448+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:41:25.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:25.469+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.292 seconds
[2024-09-01T18:41:56.108+0000] {processor.py:157} INFO - Started process (PID=4523) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:56.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:41:56.111+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:41:56.111+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:56.395+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:41:56.390+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:41:56.396+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:41:56.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.314 seconds
[2024-09-01T18:42:27.017+0000] {processor.py:157} INFO - Started process (PID=4584) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:27.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:42:27.020+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:42:27.019+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:27.290+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:42:27.286+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:42:27.292+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:27.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.297 seconds
[2024-09-01T18:42:58.193+0000] {processor.py:157} INFO - Started process (PID=4644) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:58.194+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:42:58.196+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:42:58.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:58.470+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:42:58.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:42:58.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:42:58.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.296 seconds
[2024-09-01T18:43:29.389+0000] {processor.py:157} INFO - Started process (PID=4704) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:43:29.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:43:29.393+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:43:29.393+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:43:29.679+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:43:29.675+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:43:29.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:43:29.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.312 seconds
[2024-09-01T18:44:00.264+0000] {processor.py:157} INFO - Started process (PID=4764) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:00.265+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:44:00.267+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:44:00.267+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:00.555+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:44:00.551+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:44:00.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:00.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.315 seconds
[2024-09-01T18:44:31.557+0000] {processor.py:157} INFO - Started process (PID=4824) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:31.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:44:31.560+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:44:31.560+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:31.841+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:44:31.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:44:31.842+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:44:31.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.303 seconds
[2024-09-01T18:45:02.658+0000] {processor.py:157} INFO - Started process (PID=4884) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:02.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:45:02.661+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:45:02.661+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:02.930+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:45:02.925+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:45:02.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:02.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.293 seconds
[2024-09-01T18:45:33.849+0000] {processor.py:157} INFO - Started process (PID=4944) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:33.850+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:45:33.853+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:45:33.852+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:34.180+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:45:34.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:45:34.181+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:45:34.196+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.352 seconds
[2024-09-01T18:46:05.055+0000] {processor.py:157} INFO - Started process (PID=5003) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:05.056+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:46:05.058+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:46:05.058+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:05.327+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:46:05.323+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:46:05.329+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:05.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.294 seconds
[2024-09-01T18:46:36.197+0000] {processor.py:157} INFO - Started process (PID=5063) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:36.198+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:46:36.200+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:46:36.199+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:36.571+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:46:36.567+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:46:36.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:46:36.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.393 seconds
[2024-09-01T18:47:07.376+0000] {processor.py:157} INFO - Started process (PID=5123) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:07.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:47:07.379+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:47:07.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:07.770+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:47:07.766+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:47:07.771+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:07.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.414 seconds
[2024-09-01T18:47:38.691+0000] {processor.py:157} INFO - Started process (PID=5183) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:38.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:47:38.697+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:47:38.697+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:39.127+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:47:39.123+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:47:39.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:47:39.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.457 seconds
[2024-09-01T18:48:10.086+0000] {processor.py:157} INFO - Started process (PID=5243) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:10.087+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:48:10.090+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:48:10.090+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:10.497+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:48:10.492+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:48:10.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:10.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.429 seconds
[2024-09-01T18:48:40.664+0000] {processor.py:157} INFO - Started process (PID=5303) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:40.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:48:40.666+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:48:40.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:41.051+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:48:41.046+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:48:41.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:48:41.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.405 seconds
[2024-09-01T18:49:11.933+0000] {processor.py:157} INFO - Started process (PID=5363) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:11.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:49:11.936+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:49:11.936+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:12.322+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:49:12.317+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:49:12.323+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:12.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.407 seconds
[2024-09-01T18:49:43.129+0000] {processor.py:157} INFO - Started process (PID=5423) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:43.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:49:43.131+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:49:43.131+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:43.518+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:49:43.514+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:49:43.519+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:49:43.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.407 seconds
[2024-09-01T18:50:14.407+0000] {processor.py:157} INFO - Started process (PID=5483) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:14.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:50:14.410+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:50:14.409+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:14.801+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:50:14.797+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:50:14.803+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:14.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.411 seconds
[2024-09-01T18:50:45.651+0000] {processor.py:157} INFO - Started process (PID=5543) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:45.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:50:45.654+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:50:45.654+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:46.065+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:50:46.060+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:50:46.066+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:50:46.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.432 seconds
[2024-09-01T18:51:16.984+0000] {processor.py:157} INFO - Started process (PID=5603) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:16.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:51:16.987+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:51:16.986+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:17.358+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:51:17.354+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:51:17.359+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:17.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.392 seconds
[2024-09-01T18:51:48.296+0000] {processor.py:157} INFO - Started process (PID=5663) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:48.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:51:48.300+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:51:48.300+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:48.687+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:51:48.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:51:48.689+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:51:48.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.415 seconds
[2024-09-01T18:52:19.474+0000] {processor.py:157} INFO - Started process (PID=5723) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:19.475+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:52:19.477+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:52:19.477+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:19.874+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:52:19.871+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:52:19.876+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:19.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.419 seconds
[2024-09-01T18:52:50.585+0000] {processor.py:157} INFO - Started process (PID=5783) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:50.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:52:50.587+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:52:50.587+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:50.998+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:52:50.993+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:52:50.999+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:52:51.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.431 seconds
[2024-09-01T18:53:21.867+0000] {processor.py:157} INFO - Started process (PID=5850) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:21.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:53:21.870+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:53:21.870+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:22.262+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:53:22.258+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:53:22.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:22.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.414 seconds
[2024-09-01T18:53:53.127+0000] {processor.py:157} INFO - Started process (PID=5910) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:53.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:53:53.131+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:53:53.131+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:53.577+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:53:53.573+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:53:53.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:53:53.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.469 seconds
[2024-09-01T18:54:24.462+0000] {processor.py:157} INFO - Started process (PID=5970) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:24.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:54:24.465+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:54:24.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:24.862+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:54:24.858+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:54:24.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:24.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.420 seconds
[2024-09-01T18:54:55.889+0000] {processor.py:157} INFO - Started process (PID=6030) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:55.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:54:55.893+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:54:55.893+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:56.453+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:54:56.450+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:54:56.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:54:56.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.584 seconds
[2024-09-01T18:55:26.582+0000] {processor.py:157} INFO - Started process (PID=6090) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:26.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:55:26.585+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:55:26.585+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:26.984+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:55:26.981+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:55:26.985+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:27.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.421 seconds
[2024-09-01T18:55:57.449+0000] {processor.py:157} INFO - Started process (PID=6150) to work on /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:57.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-09-01T18:55:57.452+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:55:57.452+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:57.822+0000] {logging_mixin.py:154} INFO - [2024-09-01T18:55:57.818+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-09-01T18:55:57.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-09-01T18:55:57.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.392 seconds
